### ISSUE TITLE
bug on request files on foem

### ISSUE THREAD

**Issue by hamadpashua** [ayman-elmalah/phplite#2]
the framework is fine, but when working with files the request cant seem to work with it. please fix that

**Comment by ayman-elmalah** [comment]
Hello [hamadpashua](https://github.com/hamadpashua) , this repo is just a code base for a tutorial to help developers in understanding how to build a framework from scratch, so it's not a framework to build projects using it, in tutorials we didn't deal with files yes, but if you need to update it to work on files it's very ok you can do it and if you have any issues just give me more details and i'll try to help you on your issues

tutorial link : https://www.youtube.com/playlist?list=PL94Ry2VeEr2i2uc_UFyGOxSRpW5a-fF5m

Thanks
